### ISSUE TITLE
Remove dependency on DtcGridBundle

### ISSUE THREAD

**Issue by DanielAGW** [mmucklo/DtcQueueBundle#113] opened 2019-07-15 22:56 UTC
Hi there,
First of all, thanks for great library, we're just implementing it and we will have it running on production shortly. 

The minor problem we are experiencing is that we are trying to create our application as small as possible, but DtcQueueBundle seems to include many unnecessary dependencies. Our app is strictly REST API with JSON responses and DtcQueueBundle on the backend running jobs. What happens after setting up our application is that we end up with Symfony forcing us to use Twig... DtcQueueBundle has a dependency on DtcGridBundle, which in turns requires Twig, which in turn creates Twig configuration file and basically changes the way our app behaves. Your library also creates public/bundles/dtcgrid and public/bundles/dtcqueue folders with content which we have to delete every single time. Seems like a lot of unnecessary overhead for a small data processing REST API app :)

I would suggest removing the dependency on DtcGridBundle. Some users (like us) will never use it because they are running their queues on redis anyway. I believe the best solution would be to have these two totally separated. Queue monitoring should be an independent library.

Do you perceive this as doable? I would be happy to work on some PR, but first it would be great to know what's your view on this. I believe the best approach would be to have a new lib called dtc-queue-monitoring-bundle which basically integrates these two and requires dtc-grid-bundle as well as dtc-queue-bundle plus provides some integration layer between them.

Thank you for your time.

Daniel

**Comment by mmucklo** [comment] 2019-07-16 05:37
That's interesting.

I could perhaps make DtcGridBundle optional or suggested (and detect it as a requirement for admin pages). I'm in the middle of a debugging session with the german locale and the latest MySQL, once I finish that, I was planning on some composer changes anyway, so I could try to slot that in for the next release.

**Comment by mmucklo** [comment] 2019-07-25 14:31
@DanielAGW I've created PR #116 which should address this.

**Comment by mmucklo** [comment] 2019-07-26 15:11
@DanielAGW This has been merged. Could you verify that the issue is fixed for you?

**Comment by DanielAGW** [comment] 2019-08-01 06:51
So sorry for the delay, I must have turned GitHub notifications off! We'll be updating our packages early next week so I'll definitely report it here.
Thank you so much for amazing support. I'm glad you liked the idea of separating these two.

Cheers!

**Comment by DanielAGW** [comment] 2019-08-06 00:02
@mmucklo  Looks and works great, thank you so much! Highly appreciated.
One sidenote, though. Each time we run `composer update` your lib is still creating `public/bundles/dtcqueue` directory, even though there is no need for it. Not a big problem, though, we added it to gitignore.

Thank you!

**Comment by mmucklo** [comment] 2019-08-06 04:16
I'm not sure yet if there's an easy way to turn off public/bundles/dtcqueue from getting created, although I can check into it.

**Comment by Sh1d0w** [comment] 2019-08-07 13:08
@mmucklo Thanks. However if I update to version 6 and don't install the grid package I get the following error:

```
In AnnotationException.php line 54:
                                                                                                                                                        
  [Doctrine\Common\Annotations\AnnotationException]                                                                                                     
  [Semantical Error] The annotation "@Dtc\GridBundle\Annotation\Grid" in class Dtc\QueueBundle\Entity\Job does not exist, or could not be auto-loaded.  
                                                                                                     
```

**Comment by mmucklo** [comment] 2019-08-11 06:23
@Sh1d0w Sorry for the delay in reply. For ORM and ODM it's still required to have mmucklo/grid-bundle installed.

I need to look into a way to decouple this if possible.

**Comment by mmucklo** [comment] 2019-08-12 07:15
@Sh1d0w I think I may have fixed it in the 6.0.2 release.

Let me know if it works out for you. In the mean time I'm trying to setup a test locally.

**Comment by Sh1d0w** [comment] 2019-08-13 04:59
@mmucklo Thanks for the quick response! All working good now  👍

**Comment by Sh1d0w** [comment] 2019-08-13 06:03
Actually, still getting the error:

[Doctrine\Common\Annotations\AnnotationException]                                                                                                     
  [Semantical Error] The annotation "@Dtc\GridBundle\Annotation\Grid" in class Dtc\QueueBundle\Entity\Job does not exist, or could not be auto-loaded.  

:(

**Comment by Sh1d0w** [comment] 2019-08-13 06:11
@mmucklo I guess the problem here is because if we don't install the package, you don't have the annotation itself, and it tries to load the annotation class before IgnoreAnnotation.

Can't we just remove this functionality from this package, I think the admin panel for monitoring the queues should be complete ely distinct and optional feature, possibly provided as separate bundle instead of shipping it with this package. 

After all if we use it in pure API env, it is obsolete anyways and just a adds bunch of dependencies that are not needed.

**Comment by mmucklo** [comment] 2019-08-13 07:54
@Sh1d0w I'm able to reproduce this now, working on a fix. Give me a couple of days or so.

**Comment by mmucklo** [comment] 2019-08-15 07:32
@Sh1d0w I've spent a little time on it now - it looks like this will require removing the DtcGridBundle annotations as there's no real way to completely ignore them as I thought at first (the @IgnoreAnnotation and related methods don't appear to work in that manner).

I'm going to look into removing the annotations and getting their effect a different way, but it may take a little more time, maybe like a week.

**Comment by Sh1d0w** [comment] 2019-08-15 08:04
@mmucklo Great thanks for your time looking into this! I am really looking forward to it! Thanks for the quick responses in this thread.

**Comment by Sh1d0w** [comment] 2019-09-11 12:51
@mmucklo Do you have any update on this?

**Comment by mmucklo** [comment] 2019-09-12 05:23
@Sh1d0w I got a little busy the end of last month, but I've been steadily working on DtcGridBundle recently, but it's just taking a little longer than I expected.

Thanks for your patience.

**Comment by Sh1d0w** [comment] 2019-09-12 05:25
@mmucklo No worries, just wanted to get update, please don't feel pressured on this. Really appreciate you putting time into this. Thanks!

**Comment by mmucklo** [comment] 2020-03-26 04:22
@DanielAGW, @Sh1d0w I don't know if either one of you are still using the bundle, but after a significant effort, I finally have this working.

I've removed the Annotations from the files and now use a new yaml file loader I developed in grid-bundle to pass the column definitions, when the grid-bundle is in use.

I've verified locally that decoupling does appear to work.

**Closed** 2020-06-10 01:44 UTC
