### ISSUE TITLE
Problem with german bundle and microtime

### ISSUE THREAD

**Issue by cmaerz** [mmucklo/DtcQueueBundle#98] opened 2018-11-26 08:15 UTC
Hi,

I found an incompatibility with the bundle, PHP 7.2 and the german locale setting. 

In the german locale setting the decimal separator is a comma instead of a dot. The system checks for a dot in the microtime what isn't working. If you remove the first parameter at microtime it just returns a string with a . and it should work.

Greetings from Germany,

Christian

**Comment by mmucklo** [comment] 2019-04-06 06:33
@cmaerz sorry for the delay, I've been tied up for months now. I think I can fix this, yes

**Comment by mmucklo** [comment] 2019-06-23 02:46
@cmaerz 

I tried to reproduce this a bit, but even when I change the locale to German, microtime() still returns a '.'

```php
<?php

$loc_de = setlocale(LC_ALL, 'de_DE@euro', 'de_DE', 'de', 'ge');

$locale_info = localeconv();

print_r($locale_info);
print_r($loc_de);
var_dump($loc_de);
print_r(microtime());
```

```sh
Array
(
    [decimal_point] => ,
    [thousands_sep] =>
    [int_curr_symbol] => EUR
    [currency_symbol] => Eu
    [mon_decimal_point] => ,
    [mon_thousands_sep] => .
    [positive_sign] =>
    [negative_sign] => -
    [int_frac_digits] => 2
    [frac_digits] => 2
    [p_cs_precedes] => 1
    [p_sep_by_space] => 0
    [n_cs_precedes] => 1
    [n_sep_by_space] => 0
    [p_sign_posn] => 1
    [n_sign_posn] => 1
    [grouping] => Array
        (
            [0] => 127
        )

    [mon_grouping] => Array
        (
            [0] => 3
            [1] => 3
        )

)
de_DEstring(5) "de_DE"
0.92731000 1561257625
```

I think the code you're referring to is here (in Util/Util.php):

I could change the strpos to look for '.' or ',' I suppose which could work, but I'd be curious as too what your (or anyone else's) microtome is returning.

```php
    public static function getMicrotimeStr()
    {
        $parts = explode(' ', microtime());
        $pos1 = strpos($parts[0], '.');

        $timeU = $parts[1].'.'.substr($parts[0], $pos1 + 1, 6);

        return $timeU;
    }
```

**Comment by cmaerz** [comment] 2019-06-25 08:35
Hey,

tbh I have no idea how i fixed that after all. Maybe just add the check for both '.' and ',' is a good idea. As it doesn't break anything. 

I had this problem on two different projects and different servers. Maybe it has something todo with the framework i use. http://www.pimcore.org/

Thanks for your help.

**Comment by mmucklo** [comment] 2019-07-09 06:17
@cmaerz Ok, I tried, tried, and tried to reproduce this.

I eventually compiled PHP from source, and traced things out.

microtime() will never output a comma, it will always be a decimal at least through the present version of PHP.

It's a feature/bug traced down to this line of code which checks that the format specifier is "f" before it pays attention to LOCALE specific decimal point options (otherwise it uses '.')
https://github.com/php/php-src/blob/master/main/spprintf.c#L639

This code is the same all the way back to PHP 5.6.40 at least:
https://github.com/php/php-src/blob/PHP-5.6.40/main/spprintf.c#L630

The issue is that microtime requests the format in %.8F (note the capital 'F'):
https://github.com/php/php-src/blob/master/ext/standard/microtime.c#L81

Which is the same all the way back to 5.6.40 at least:
https://github.com/php/php-src/blob/PHP-5.6.40/ext/standard/microtime.c#L86

So the capital F trips up the function and it doesn't use the locale-specific decimal point operator.

I'm pretty sure that it's a bug with PHP as doing a capital F in regular printf in C works:

```c
#include <stdio.h>
#include <locale.h>

int main(int argc, char**argv) {
	setlocale(LC_ALL, "de_DE.UTF-8");
	printf("%.8f\n", 0.12345);
	printf("%.8F\n", 0.12335);
	return 0;
}
```

You may want to do this first (if you're using ubuntu like I am) before compiling the above code:
```
locale-gen de_DE.UTF-8
```

**Comment by mmucklo** [comment] 2019-07-09 06:19
@cmaerz Is it possible that it was how things were being passed elsewhere (maybe to mysql?) as I'm pretty sure it's not the getMicrotimeStr() function anymore.

**Comment by mmucklo** [comment] 2019-07-09 06:47
@cmaerz On the microtime() formating issue I did file a php bug here: https://bugs.php.net/bug.php?id=78265

This is not the issue you were encountering, however, which makes me suspect the database layer or some other hand-off point rather than the '.' search.

I could probably add the ',' check into the code (or do something similar) just to be extra safe (in case they actually fix the PHP bug) - in fact I may do that, but I still think the error was some where else.

Let me know if you have any other insights.

**Comment by mmucklo** [comment] 2019-07-09 15:35
@cmaerz Turns out the PHP "bug" is actually expected behavior at least as of 7.3.

I'm still tracing to see if I can reproduce things in 7.2 or lower (as the implementation of microtime changed slightly). Any other insights you have would be great.

**Comment by mmucklo** [comment] 2019-07-11 07:54
@cmaerz Just an update - I traced back into 7.2 and it does use a different printing function, but it leads to similar PHP-style formatting code as it calls an overridden system function (snprintf) to do the formatting which apparently PHP internals redefines (http://www.phpinternalsbook.com/php7/internal_types/strings/printing_functions.html).

In other words, I'm fairly sure that microtime() only returns the "." version when called in the default-no-argument manner.

I don't see a case where microtime ever returns a "," value in the default-argument case even if the locale is changed.

If you (or anyone else) comes up with a reproducible test case, it would be great.

My last test might be to go back to 7.0 or 5.6 and see if they behave the same, although I'm guessing there's not going to be a difference.

**Comment by cmaerz** [comment] 2019-07-11 09:02
Hey,

Sorry for the delay.. was on holidays for two and a half weeks and I'm deep into a customer Project currently.

I can't reproduce it either now. I downgraded that server to 7.2 and it still seems to work. I'm 100% sure that problem was real cause i had that same struggle on two different projects, maybe some patch release fixed it in the meantime. 

I had the Problem when the Locale was on de_DE.utf8 and didn't have it on en_US.utf8

Very strange. Thanks for your effort and sorry for stealing your time then.

**Comment by mmucklo** [comment] 2019-07-12 08:47
@cmaerz believe it or not, I think I may have fixed it.

I checked in the changes into master, but haven't tagged the branch yet as I'm trying to run the test suite against the German locale.

Presently I'm hitting a memory issue on my local machine running 7.3.6 in a docker container configured for the de_DE locale, however the Travis tests up through 7.2 are passing, so I don't think anything is broken at least in the normal locales.

I'll have to take a look later and see if I can get the tests to work.

**Comment by i-telligence-af** [comment] 2019-07-19 15:52
I'm having the same issue, also using Pimcore.

Running Symfony commands works fine, but when going through a http request I'm having the same problem. That is a bit strange, because I'm using the same PHP executable in both cases and date_default_timezone_get() returns "Europe/Berlin" in both cases.  

I tried dev-master, but unfortunately that didn't help either.

**Comment by mmucklo** [comment] 2019-07-20 06:13
@i-telligence-af I've discovered the problem goes a bit deeper.

Doctrine seems to have some kind of bug as far as I've ascertained that converts floats into numbers with ',' instead of the SQL standard '.' in the german locale.

I have a patch to DtcQueueBundle to work around the issue, perhaps, but I was working on a submission to the Doctrine folks so they could fix/address the issue.

You're welcome to test the patch if you can sync to this branch (if it works maybe I can make a flag for it and submit it to master): https://github.com/mmucklo/DtcQueueBundle/tree/doctrine-bug

**Comment by i-telligence-af** [comment] 2019-07-22 09:42
@mmucklo thanks for the quick response!

Your patch seems to work :) I'll continue using it for now. Let me know if you want to submit it to master, and eventually a new release. I'll switch back then.

Thanks again!

**Comment by mmucklo** [comment] 2019-07-22 15:07
@i-telligence-sf I’m still trying to reproduce this in a vanilla doctrine install. I can let you know once I have the root cause narrowed down, and at that time determine what sort of “permanent” fix is appropriate, although likely either way something will get merged to master.

**Comment by mmucklo** [comment] 2019-07-23 06:02
@cmaerz and @i-telligence-af:

It's a doctrine bug in the Mysqli driver. I've submitted a bug report to doctrine that should be appearing on this issue now. For now the work around branch should work, but I may merge it to master if the doctrine folks don't respond to the bug quickly enough.

**Comment by mmucklo** [comment] 2019-07-24 05:03
@i-telligence-af 

Okay, I created a new branch with a more permanent fix. When the tests pass, I will merge it. There will be a flag in the configuration called "locale_fix" which you'll need to set to true:

```yaml
   locale_fix: true
```

This will turn the ORM fix behavior on.

**Comment by mmucklo** [comment] 2019-07-25 04:35
@i-telligence-af 

I've merged my changes into the main branch and tagged things as release 5.1.1.

Please let me know if setting **locale_fix: true** works for you.

**Comment by i-telligence-af** [comment] 2019-07-25 09:00
> @i-telligence-af
> 
> I've merged my changes into the main branch and tagged things as release 5.1.1.
> 
> Please let me know if setting **locale_fix: true** works for you.

hey @mmucklo , it works, many thanks!

**Closed** 2019-07-25 14:28 UTC
